### ISSUE TITLE
路径相同的问题

### ISSUE THREAD

**Issue by pengxuyang** [gauseen/nuxt-proxy#1]
比如远程登录接口为 login，本地的登录页路径也为 login 
配置后 访问本地登录页 会直接请求远程登录接口

**Comment by gauseen** [comment]
不好意思，刚刚看到
你请求` URL` 没有 统一的标识符吗，例如，都是以 `/api `开头之类的字段，
如果你只配置` /login` 那只对这一个接口有代理效果
